# Generated by Django 5.1.2 on 2024-10-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_fav_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_color',
        ),
    ]
